Test enhancement
phpexpertsinc/workday-planner pull request #5
Opened 2018-08-13 14:56 UTC by peter279k

# Changed log
- Using the assertion APIs to assert the correct assertions.
- Using the `DataProvider` to collect the test cases.
- Adding the `expectedExceptionMessage` to assert the expected exception message.
- Add the Travis CI build. Please look at that the [Travis CI build log](https://travis-ci.org/peter279k/workday-planner/builds/415484949).

2018-08-23 17:43 UTC, hopeseekr requested changes
This is great! THANK YOU SO MUCH!

2018-08-23 17:43 UTC, hopeseekr commented on tests/HolidayDetectorTest.php
> -            unlink($invalidFile);
It does not seem like your version removes the invalid data file.

2018-08-23 18:01 UTC, peter279k commented on tests/HolidayDetectorTest.php
> +        $this->expectExceptionMessage("Invalid holiday data for 'invalid'.");
I replace the `try...catch` expected exception approach with the `expectException` approach.
And I think this should be better than previous approach.

2018-10-31 19:57 UTC, hopeseekr approved these changes

2019-03-09 06:37 UTC, merged

2019-03-09 06:38 UTC, hopeseekr commented
@peter279k I greatly apologize for approving the PR way way back on Halloween 2018 yet not hitting the Merge button until 4 1/2 months later.

Thank you **so** much!! I really appreciate your contribution!

2019-03-09 08:16 UTC, peter279k commented
Hi @hopeseekr, thank you for your reply.

Never mind. I hope you concern this and merge this PR finally :).